name: skyrockit
favicon: null
layout_spectrum: 0.4799595808144659
typography_spectrum: 0.6718614280689508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7631725501269102
  lightness: 0.10991772613488138
  saturation: 0.87027349579148
  rhythmicContrast: 0.994279618607834
purpose: []
